name: My first workflow
run-name: 🚀🚀🚀🚀🚀
on: 
  push:
    branches:
      - caca
jobs:
  echo-pipeline:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install --global @mikemcbride/dad-jokes
      - run: dad-jokes
      - name: Create report file
        run: dad-jokes > report.txt
      - name: List files in the repository 2
        run: ls ${{ github.workspace }}
   
      - name: Déployer sur gh-pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: main
          FOLDER: ./
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          MESSAGE: "Build: ({sha}) {msg}" 